version: "3.9"

volumes:
  postgres-data:
  redis-data:
  storage:

services:
  postgres:
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - chatwoot.env

  redis:
    image: redis:7.0-alpine
    restart: unless-stopped
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    volumes:
      - redis-data:/data
    env_file:
      - chatwoot.env

  chatwoot:
    image: chatwoot/chatwoot:latest
    restart: unless-stopped
    entrypoint: /app/docker/entrypoints/rails.sh # Caminho CORRETO e VERIFICADO
    command: sh -c "bundle exec rails db:prepare && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - postgres
      - redis
    ports:
      - "3001:3000"
    env_file:
      - chatwoot.env
    volumes:
      - storage:/app/storage

  sidekiq:
    image: chatwoot/chatwoot:latest
    restart: unless-stopped
    entrypoint: /app/docker/entrypoints/rails.sh # Caminho CORRETO e VERIFICADO
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    env_file:
      - chatwoot.env
    volumes:
      - storage:/app/storage
